# Generated by Django 4.1.1 on 2022-09-07 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop', models.CharField(max_length=20)),
                ('menu', models.CharField(choices=[('food', 'FOOD'), ('sweet', 'SWEET'), ('drinks', 'DRINKS')], default='food', max_length=10)),
                ('price', models.FloatField()),
                ('rest_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
